#!/bin/bash
# Creates a test database + tables in the mock Glue catalog (moto) so
# there's something for WaggleDance to route to.
set -euo pipefail

export AWS_ACCESS_KEY_ID=test
export AWS_SECRET_ACCESS_KEY=test
export AWS_DEFAULT_REGION=us-east-1

ENDPOINT=http://localhost:5000

aws --endpoint-url "$ENDPOINT" glue create-database \
  --database-input '{"Name": "testdb"}'

aws --endpoint-url "$ENDPOINT" glue create-table \
  --database-name testdb \
  --table-input '{
    "Name": "no_tabletype",
    "StorageDescriptor": {
      "Columns": [{"Name": "id", "Type": "bigint"}],
      "Location": "s3://test-bucket/testdb/no_tabletype/",
      "InputFormat": "org.apache.hadoop.mapred.TextInputFormat",
      "OutputFormat": "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
    }
  }'

aws --endpoint-url "$ENDPOINT" glue create-table \
  --database-name testdb \
  --table-input '{
    "Name": "example_traces_table",
    "Owner": "test-owner",
    "Retention": 0,
    "StorageDescriptor": {
      "Columns": [
        {"Name": "id", "Type": "string"},
        {"Name": "trace_id", "Type": "string"},
        {"Name": "parent_run_ids", "Type": "array<string>"},
        {"Name": "name", "Type": "string"},
        {"Name": "start_time", "Type": "timestamp"},
        {"Name": "is_root", "Type": "boolean"},
        {"Name": "total_cost", "Type": "double"},
        {"Name": "total_tokens", "Type": "bigint"}
      ],
      "Location": "s3://test-bucket/testdb/example_traces_table/",
      "InputFormat": "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat",
      "OutputFormat": "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat",
      "Compressed": false,
      "NumberOfBuckets": -1,
      "SerdeInfo": {
        "SerializationLibrary": "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe",
        "Parameters": {
          "serialization.format": "1",
          "path": "s3://test-bucket/testdb/example_traces_table/"
        }
      },
      "BucketColumns": [],
      "SortColumns": [],
      "Parameters": {},
      "StoredAsSubDirectories": false
    },
    "PartitionKeys": [
      {"Name": "tenant_id", "Type": "string"},
      {"Name": "session_id", "Type": "string"},
      {"Name": "start_date", "Type": "date"}
    ],
    "TableType": "MANAGED_TABLE",
    "Parameters": {
      "classification": "parquet",
      "spark.sql.sources.provider": "parquet",
      "spark.sql.partitionProvider": "catalog",
      "spark.sql.sources.schema.numPartCols": "3",
      "spark.sql.sources.schema.partCol.0": "tenant_id",
      "spark.sql.sources.schema.partCol.1": "session_id",
      "spark.sql.sources.schema.partCol.2": "start_date"
    }
  }'

aws --endpoint-url "$ENDPOINT" glue create-table \
  --database-name testdb \
  --table-input '{
    "Name": "example_s3_stream_table",
    "Owner": "test-owner",
    "Retention": 0,
    "StorageDescriptor": {
      "Columns": [
        {"Name": "value2", "Type": "bigint", "Comment": ""},
        {"Name": "hotel_name", "Type": "string", "Comment": ""},
        {"Name": "hotelprice", "Type": "double", "Comment": ""}
      ],
      "Location": "s3://test-bucket/testdb/example_s3_stream_table/",
      "InputFormat": "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat",
      "OutputFormat": "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat",
      "Compressed": false,
      "NumberOfBuckets": -1,
      "SerdeInfo": {
        "SerializationLibrary": "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe",
        "Parameters": {
          "serialization.format": "1",
          "hive.serialization.extend.nesting.levels": "true",
          "hive.serialization.extend.additional.nesting.levels": "true"
        }
      },
      "BucketColumns": [],
      "SortColumns": [],
      "Parameters": {},
      "StoredAsSubDirectories": false
    },
    "PartitionKeys": [
      {"Name": "acquisition_date", "Type": "string"}
    ],
    "TableType": "EXTERNAL_TABLE",
    "Parameters": {
      "bucketing_version": "2",
      "classification": "parquet",
      "EXTERNAL": "TRUE",
      "cleanup.remove-unreferenced-data": "true",
      "comment": "Table generated by a data pipeline, derived from source table lz_data.example_s3_stream_table"
    }
  }'

aws --endpoint-url "$ENDPOINT" glue create-table \
  --database-name testdb \
  --table-input '{
    "Name": "test_external_iceberg_table_with_serdes",
    "Owner": "appuser",
    "LastAccessTime": 1536,
    "Retention": 2147483647,
    "StorageDescriptor": {
      "Columns": [
        {"Name": "hotel_name", "Type": "string"},
        {"Name": "hotel_id", "Type": "int"},
        {"Name": "acq_hour", "Type": "int"},
        {"Name": "acq_date", "Type": "date"}
      ],
      "Location": "s3://test-bucket/testdb/test_external_iceberg_table_with_serdes",
      "InputFormat": "org.apache.hadoop.mapred.FileInputFormat",
      "OutputFormat": "org.apache.hadoop.mapred.FileOutputFormat",
      "Compressed": false,
      "NumberOfBuckets": 0,
      "SerdeInfo": {
        "SerializationLibrary": "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe",
        "Parameters": {}
      },
      "BucketColumns": [],
      "SortColumns": [],
      "Parameters": {},
      "StoredAsSubDirectories": false
    },
    "PartitionKeys": [],
    "TableType": "EXTERNAL_TABLE",
    "Parameters": {
      "numRows": "5",
      "engine.hive.lock-enabled": "false",
      "default-partition-spec": "{\"spec-id\":0,\"fields\":[{\"name\":\"acq_date\",\"transform\":\"identity\",\"source-id\":5,\"field-id\":1000},{\"name\":\"acq_hour\",\"transform\":\"identity\",\"source-id\":4,\"field-id\":1001}]}",
      "write.metadata.delete-after-commit.enabled": "true",
      "uuid": "98b476e8-b47e-44e2-974f-bcb0a341259d",
      "EXTERNAL": "TRUE",
      "write.data.path": "s3://test-bucket/testdb/test_external_iceberg_table_with_serdes/data",
      "write.metadata.previous-versions-max": "100",
      "numFiles": "1",
      "table_type": "ICEBERG",
      "previous_metadata_location": "s3://test-bucket/testdb/test_external_iceberg_table_with_serdes/metadata/00000-d6a9128b-58bd-44d9-acbe-d0493833bdcc.metadata.json",
      "current-snapshot-id": "6299780294964445581",
      "write.metadata.path": "s3://test-bucket/testdb/test_external_iceberg_table_with_serdes/metadata",
      "write.parquet.compression-codec": "snappy",
      "current-schema": "{\"type\":\"struct\",\"schema-id\":0,\"fields\":[{\"id\":2,\"name\":\"hotel_name\",\"required\":true,\"type\":\"string\"},{\"id\":3,\"name\":\"hotel_id\",\"required\":true,\"type\":\"int\"},{\"id\":4,\"name\":\"acq_hour\",\"required\":true,\"type\":\"int\"},{\"id\":5,\"name\":\"acq_date\",\"required\":true,\"type\":\"date\"}]}",
      "totalSize": "2667",
      "current-snapshot-timestamp-ms": "1758179722041",
      "metadata_location": "s3://test-bucket/testdb/test_external_iceberg_table_with_serdes/metadata/00001-8372c9c3-d762-43de-aa8a-34de2034affa.metadata.json",
      "snapshot-count": "1"
    }
  }'

aws --endpoint-url "$ENDPOINT" glue create-table \
  --database-name testdb \
  --table-input '{
    "Name": "test_external_iceberg_table_no_serde",
    "Owner": "appuser",
    "LastAccessTime": 1536,
    "Retention": 2147483647,
    "StorageDescriptor": {
      "Columns": [
        {"Name": "hotel_name", "Type": "string"},
        {"Name": "hotel_id", "Type": "int"},
        {"Name": "acq_hour", "Type": "int"},
        {"Name": "acq_date", "Type": "date"}
      ],
      "Location": "s3://test-bucket/testdb/test_external_iceberg_table_no_serde",
      "Compressed": false,
      "NumberOfBuckets": 0,
      "BucketColumns": [],
      "SortColumns": [],
      "Parameters": {},
      "StoredAsSubDirectories": false
    },
    "PartitionKeys": [],
    "TableType": "EXTERNAL_TABLE",
    "Parameters": {
      "numRows": "5",
      "engine.hive.lock-enabled": "false",
      "default-partition-spec": "{\"spec-id\":0,\"fields\":[{\"name\":\"acq_date\",\"transform\":\"identity\",\"source-id\":5,\"field-id\":1000},{\"name\":\"acq_hour\",\"transform\":\"identity\",\"source-id\":4,\"field-id\":1001}]}",
      "write.metadata.delete-after-commit.enabled": "true",
      "uuid": "98b476e8-b47e-44e2-974f-bcb0a341259d",
      "EXTERNAL": "TRUE",
      "write.data.path": "s3://test-bucket/testdb/test_external_iceberg_table_no_serde/data",
      "write.metadata.previous-versions-max": "100",
      "numFiles": "1",
      "table_type": "ICEBERG",
      "previous_metadata_location": "s3://test-bucket/testdb/test_external_iceberg_table_no_serde/metadata/00000-d6a9128b-58bd-44d9-acbe-d0493833bdcc.metadata.json",
      "current-snapshot-id": "6299780294964445581",
      "write.metadata.path": "s3://test-bucket/testdb/test_external_iceberg_table_no_serde/metadata",
      "write.parquet.compression-codec": "snappy",
      "current-schema": "{\"type\":\"struct\",\"schema-id\":0,\"fields\":[{\"id\":1,\"name\":\"event_header\",\"required\":true,\"type\":{\"type\":\"struct\",\"fields\":[{\"id\":6,\"name\":\"event_uuid\",\"required\":true,\"type\":\"string\"},{\"id\":7,\"name\":\"event_name\",\"required\":true,\"type\":\"string\"},{\"id\":8,\"name\":\"event_published_datetime_utc\",\"required\":true,\"type\":\"timestamptz\"}]}},{\"id\":2,\"name\":\"hotel_name\",\"required\":true,\"type\":\"string\"},{\"id\":3,\"name\":\"hotel_id\",\"required\":true,\"type\":\"int\"},{\"id\":4,\"name\":\"acq_hour\",\"required\":true,\"type\":\"int\"},{\"id\":5,\"name\":\"acq_date\",\"required\":true,\"type\":\"date\"}]}",
      "totalSize": "2667",
      "current-snapshot-timestamp-ms": "1758179722041",
      "metadata_location": "s3://test-bucket/testdb/test_external_iceberg_table_no_serde/metadata/00001-8372c9c3-d762-43de-aa8a-34de2034affa.metadata.json",
      "snapshot-count": "1"
    }
  }'

aws --endpoint-url "$ENDPOINT" glue create-table \
  --database-name testdb \
  --table-input '{
    "Name": "example_iceberg_table_no_serde",
    "Retention": 0,
    "StorageDescriptor": {
      "Columns": [
        {"Name": "id", "Type": "string"}
      ],
      "Location": "s3://test-bucket/testdb/example_iceberg_table_no_serde",
      "Compressed": false,
      "NumberOfBuckets": 0,
      "SortColumns": [],
      "StoredAsSubDirectories": false
    },
    "TableType": "EXTERNAL_TABLE",
    "Parameters": {
      "previous_metadata_location": "s3://test-bucket/testdb/example_iceberg_table_no_serde/metadata/00000-8d5de7e0-fba3-4b1e-80f9-219fc04ee8f7.metadata.json",
      "origin-location": "US",
      "classification": "confidential",
      "data-product": "example-data-product",
      "odcs.spec.version": "v1.0.0",
      "storage-location": "US",
      "domain": "example-domain",
      "metadata_location": "s3://test-bucket/testdb/example_iceberg_table_no_serde/metadata/00001-c916a1da-fcc9-4938-a5c6-b515fe269116.metadata.json",
      "tagging-specification": "example-governance-tags-v2",
      "application-name": "example-app",
      "owner": "team@example.com",
      "table_type": "ICEBERG",
      "odcs.kind": "DataContract",
      "odcs.contract": "{\"kind\":\"DataContract\",\"specVersion\":\"v1.0.0\",\"metadata\":{\"name\":\"example_iceberg_table_no_serde\",\"dataProduct\":\"example-data-product\",\"status\":\"DRAFT\",\"certification\":{\"medallionClassification\":\"BRONZE\",\"operationalState\":\"DEVELOPMENT\",\"deprecationDate\":null},\"contractOwner\":{\"team\":\"Example Team\",\"email\":\"team@example.com\",\"appName\":\"example-app\"},\"retentionCode\":\"IT600\",\"version\":null},\"targetEntity\":{\"type\":\"table\",\"fqn\":\"testdb.example_iceberg_table_no_serde\",\"tableFormat\":null,\"hiveFileFormat\":null},\"view\":null,\"materializedView\":null,\"optimization\":null}"
    }
  }'

echo "Seeded testdb.no_tabletype, testdb.example_traces_table, testdb.example_s3_stream_table, testdb.test_external_iceberg_table_with_serdes, testdb.test_external_iceberg_table_no_serde, and testdb.example_iceberg_table_no_serde in mock Glue at $ENDPOINT"
