name: Docker Test Build

on:
  pull_request:
  workflow_dispatch:
    inputs:
      pushImage:
        description: "Push docker image? (default is: false)"
        required: false
        default: 'false'

jobs:
  apiary-docker-image:
    name: Apiary Docker Image Checks
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Ensure Apiary Docker Image Builds.
      uses: docker/build-push-action@v1.1.0
      with:
        dockerfile: "Dockerfile"
        always_pull: true
        push: ${{ github.event.inputs.pushImage }}
